language: node_js
node_js:
  - "16"

notifications:
  email: false

install:
  - npm install

jobs:
  include:
    - name: "Unit Tests"
      script: npm test
    # - name: "Audit"
    #   script: npm audit || echo \"audit found some vulnerabilities.\"
    - name: "Docs"
      script: npm run doc
    - name: "Lint"
      script: npm run lint
    - if: branch = master
      stage: "deploy"
      script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - npm run release:publish
      skip_cleanup: true
